# Codecov configuration
# https://docs.codecov.io/docs/codecov-yaml

coverage:
  status:
    project:
      default:
        target: 65%
        threshold: 1%
        informational: true
    patch:
      default:
        target: 60%
        threshold: 5%
        informational: true

comment:
  layout: diff, flags, files
  behavior: default
  require_changes: false
  require_base: false
  require_head: true

ignore:
- tests/
- '**/__pycache__/'
- '**/venv/'
- '**/.venv/'
- scripts/
- '**/__init__.py'

flags:
  unit:
    paths:
    - src/
    carryforward: true
